### ISSUE TITLE
Original mantainer no longer maintain this wifi driver

### ISSUE THREAD

**Issue by AlexiaChen** [SpringDarkGroup/rtl8821ce#1]
https://github.com/tomaspinho/rtl8821ce/issues/26
I will continue maintain. Cause I bought a xiaomi laptop with a shit rtl8821ce wifi chip that not officially support on linux

**Comment by JackLilhammers** [comment]
I'm not experienced with driver development, but I'll try to help since I have the same shitty card

**Comment by AlexiaChen** [comment]
I've found that this driver has been maintained by others.

https://unix.stackexchange.com/questions/379049/realtek-rtl8821ce-wifi-driver-problem-in-linux-mint-18-2

 https://github.com/endlessm/linux/tree/master/drivers/net/wireless/rtl8821ce

@JackLilhammers

**Comment by JackLilhammers** [comment]
@AlexiaChen that's the original repo. endless OS uses a modified kernel that includes the driver we need. get_sources.sh clones from there

**Comment by AlexiaChen** [comment]
@JackLilhammers 
Oh, sorry, I didn't notice the bash get_source.sh. Then I looked through the commit history of https://github.com/tomaspinho/rtl8821ce repo. The author did not maintain the driver's source code, but maintained the driver's build process to be compatible with the latest kernel. So maintaining this driver may not be a difficult task, and there is no need for maintainers to go deep into Linux driver development.

**Comment by AlexiaChen** [comment]
@JackLilhammers  

But we need to fix compilation errors to be compatible with major versions of Linux, because some of Linux kernel APIs may change frequently with kernel versions change.

currently this driver works well on my laptop with 5.0.7 kernel

**Comment by JackLilhammers** [comment]
I use both manjaro (4.19 lts) and ubuntu 18.04.2 (4.18) and it seems to work just fine.
From what I've read when I was looking for a solution fedora and solus should work too, but I haven't tested it.

**Comment by image357** [comment]
I am using Fedora 29 and this kinda works. I get occasionally system error messages (with the current endlessm version) but they seem to not break anything essential.

However, it seems that the rtl8821c driver should be in the kernel since 4.13:
https://bugs.launchpad.net/ubuntu/+source/linux-oem/+bug/1740231

I'm using 5.0.7 and can confirm that Bluetooth is working out of the box. However, wifi works only with your driver version.

**Comment by JackLilhammers** [comment]
I think they're 2 different drivers. We can hope that rtl8821ce will be mainlined soon enough

**Comment by AlexiaChen** [comment]
@JackLilhammers  Maybe it has a long way to support. kernel only support rtl8821ae https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/net/wireless/realtek/rtlwifi/rtl8821ae?id=9c66a7e5d39c410a5da1bec868d3b1442e0b5f17     This chip is older compared to rtl8821ce.   :)

**Comment by JackLilhammers** [comment]
Hopefully, with the growing adoption, will grow the need for support
